# Generated by Django 2.0 on 2018-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_module',
            fields=[
                ('module_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('precision', models.CharField(max_length=20)),
                ('feature_scores_and_ranges', models.CharField(max_length=9999)),
                ('pie_data', models.CharField(max_length=9999)),
            ],
        ),
    ]
