# Generated by Django 2.0 on 2018-03-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_module',
            old_name='precision',
            new_name='evaluate_score',
        ),
    ]
