# Generated by Django 2.0 on 2018-01-03 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_num', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='student_name', max_length=50)),
                ('score', models.FloatField(default=0.0, max_length=10)),
                ('scholarship', models.FloatField(default=0.0, max_length=10)),
                ('subsidy', models.FloatField(default=0.0, max_length=10)),
                ('have_scholarship', models.BooleanField(default=False)),
                ('have_subsidy', models.BooleanField(default=False)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_reason', models.CharField(default='', max_length=100)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 3, 14, 53, 33, 777010))),
            ],
        ),
    ]
