# Generated by Django 2.0 on 2017-12-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_num', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='student_name', max_length=50)),
                ('score', models.FloatField(default=0.0, max_length=10)),
                ('is_missing', models.BooleanField(default=False)),
                ('have_scholarship', models.BooleanField(default=False)),
                ('have_subsidy', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
