# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_num', models.CharField(default='student_num', max_length=20)),
                ('student_name', models.CharField(default='student_name', max_length=50)),
                ('score', models.FloatField(default=0.0, max_length=10)),
            ],
        ),
    ]
