# Generated by Django 2.0 on 2017-12-19 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scholarship',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='subsidy',
            field=models.FloatField(default=0.0, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 19, 16, 58, 14, 546000)),
        ),
    ]
