# Generated by Django 2.0 on 2018-04-19 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 19, 19, 27, 13, 63604)),
        ),
    ]
